FROM golang:1.21-alpine

WORKDIR /app

# Copia arquivos da raiz para o contexto correto
COPY worker/go.mod worker/go.sum ./
RUN go mod download

# Copia o código fonte
COPY worker/ .

RUN go build -o worker .

CMD ["./worker"]
